package trucnvph17923;

import Utils.Auth;
import Utils.MsgBox;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Nguyen Truc
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        // Change default icon 
        ImageIcon icon = new ImageIcon("src\\Icons\\fpt.png");
        this.setIconImage(icon.getImage());
        // Setting clock
        new Thread() { //Start - Create a clock
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
                while (true) {
                    Date d = new Date();
                    lblcock.setText(sdf.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception ex) {
                        break;
                    }
                }
            }
        }.start();
        //End - Create a clock
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnketthuc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnchuyende = new javax.swing.JButton();
        btnnguoihoc = new javax.swing.JButton();
        btnkhoahoc = new javax.swing.JButton();
        btnhocvien = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblcock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuhethong = new javax.swing.JMenu();
        mnilogin = new javax.swing.JMenuItem();
        mnidangxuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnidoimatkhau = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniketthuc = new javax.swing.JMenuItem();
        mnuquanly = new javax.swing.JMenu();
        mnichuyende = new javax.swing.JMenuItem();
        mnikhoahoc = new javax.swing.JMenuItem();
        mninguoihoc = new javax.swing.JMenuItem();
        mnihocvien = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mninhanvien = new javax.swing.JMenuItem();
        mnuthongke = new javax.swing.JMenu();
        mnibangdiem = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniluongnguoihoc = new javax.swing.JMenuItem();
        mnidiemcd = new javax.swing.JMenuItem();
        mnidoanhthu = new javax.swing.JMenuItem();
        mnutrogiup = new javax.swing.JMenu();
        mnihuongdan = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnigioithieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LẬP TRÌNH CITY EDUCATION");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btnketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stop.png"))); // NOI18N
        btnketthuc.setText("Kết thúc");
        btnketthuc.setFocusable(false);
        btnketthuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnketthuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketthucActionPerformed(evt);
            }
        });
        jToolBar1.add(btnketthuc);
        jToolBar1.add(jSeparator2);

        btnchuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lists.png"))); // NOI18N
        btnchuyende.setText("Chuyên đề");
        btnchuyende.setFocusable(false);
        btnchuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnchuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnchuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnchuyende);

        btnnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Conference.png"))); // NOI18N
        btnnguoihoc.setText("Người học");
        btnnguoihoc.setFocusable(false);
        btnnguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnnguoihoc);

        btnkhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Certificate.png"))); // NOI18N
        btnkhoahoc.setText("Khóa học");
        btnkhoahoc.setFocusable(false);
        btnkhoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkhoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkhoahoc);

        btnhocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        btnhocvien.setText("Học viên");
        btnhocvien.setFocusable(false);
        btnhocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhocvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnhocvien);
        jToolBar1.add(jSeparator6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Globe.png"))); // NOI18N
        jButton7.setText("Hướng dẫn");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1320, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logofpoly.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1320, 590));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Alarm.png"))); // NOI18N
        lblcock.setText("05:06:08 PM");
        jPanel2.add(lblcock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 120, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Info.png"))); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1320, 50));

        mnuhethong.setText("Hệ thống");

        mnilogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnilogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Key.png"))); // NOI18N
        mnilogin.setText("Đăng nhập");
        mnilogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniloginActionPerformed(evt);
            }
        });
        mnuhethong.add(mnilogin);

        mnidangxuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnidangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Exit.png"))); // NOI18N
        mnidangxuat.setText("Đăng xuất");
        mnidangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidangxuatActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidangxuat);
        mnuhethong.add(jSeparator3);

        mnidoimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Refresh.png"))); // NOI18N
        mnidoimatkhau.setText("Đổi mật khẩu");
        mnidoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoimatkhauActionPerformed(evt);
            }
        });
        mnuhethong.add(mnidoimatkhau);
        mnuhethong.add(jSeparator4);

        mniketthuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniketthuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Stop.png"))); // NOI18N
        mniketthuc.setText("Kết thúc");
        mniketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniketthucActionPerformed(evt);
            }
        });
        mnuhethong.add(mniketthuc);

        jMenuBar1.add(mnuhethong);

        mnuquanly.setText("Quản lý");

        mnichuyende.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        mnichuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lists.png"))); // NOI18N
        mnichuyende.setText("Chuyên đề");
        mnichuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnichuyendeActionPerformed(evt);
            }
        });
        mnuquanly.add(mnichuyende);

        mnikhoahoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        mnikhoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Certificate.png"))); // NOI18N
        mnikhoahoc.setText("Khóa học");
        mnikhoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikhoahocActionPerformed(evt);
            }
        });
        mnuquanly.add(mnikhoahoc);

        mninguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        mninguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Conference.png"))); // NOI18N
        mninguoihoc.setText("Người học");
        mninguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninguoihocActionPerformed(evt);
            }
        });
        mnuquanly.add(mninguoihoc);

        mnihocvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnihocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User.png"))); // NOI18N
        mnihocvien.setText("Học viên");
        mnihocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihocvienActionPerformed(evt);
            }
        });
        mnuquanly.add(mnihocvien);
        mnuquanly.add(jSeparator7);

        mninhanvien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        mninhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User group.png"))); // NOI18N
        mninhanvien.setText("Nhân viên");
        mninhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mninhanvienActionPerformed(evt);
            }
        });
        mnuquanly.add(mninhanvien);

        jMenuBar1.add(mnuquanly);

        mnuthongke.setText("Thống kê");
        mnuthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuthongkeActionPerformed(evt);
            }
        });

        mnibangdiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        mnibangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Card file.png"))); // NOI18N
        mnibangdiem.setText("Bảng điểm");
        mnibangdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnibangdiemActionPerformed(evt);
            }
        });
        mnuthongke.add(mnibangdiem);
        mnuthongke.add(jSeparator8);

        mniluongnguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        mniluongnguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Clien list.png"))); // NOI18N
        mniluongnguoihoc.setText("Lượng người học");
        mniluongnguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniluongnguoihocActionPerformed(evt);
            }
        });
        mnuthongke.add(mniluongnguoihoc);

        mnidiemcd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_MASK));
        mnidiemcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Bar chart.png"))); // NOI18N
        mnidiemcd.setText("Điểm chuyên đề");
        mnidiemcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidiemcdActionPerformed(evt);
            }
        });
        mnuthongke.add(mnidiemcd);

        mnidoanhthu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        mnidoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Dollar.png"))); // NOI18N
        mnidoanhthu.setText("Doanh thu");
        mnidoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnidoanhthuActionPerformed(evt);
            }
        });
        mnuthongke.add(mnidoanhthu);

        jMenuBar1.add(mnuthongke);

        mnutrogiup.setText("Trợ giúp");

        mnihuongdan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnihuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Globe.png"))); // NOI18N
        mnihuongdan.setText("Hướng dẫn sử dụng");
        mnihuongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnihuongdanActionPerformed(evt);
            }
        });
        mnutrogiup.add(mnihuongdan);
        mnutrogiup.add(jSeparator5);

        mnigioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Brick house.png"))); // NOI18N
        mnigioithieu.setText("Giới thiệu sản phẩm");
        mnigioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnigioithieuActionPerformed(evt);
            }
        });
        mnutrogiup.add(mnigioithieu);

        jMenuBar1.add(mnutrogiup);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketthucActionPerformed
        openKetthuc();
    }//GEN-LAST:event_btnketthucActionPerformed

    private void mninhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninhanvienActionPerformed
        openNhanvien();
    }//GEN-LAST:event_mninhanvienActionPerformed

    private void mninguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mninguoihocActionPerformed
        openNguoihoc();
    }//GEN-LAST:event_mninguoihocActionPerformed

    private void mnidoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoimatkhauActionPerformed
        if (Auth.isLogin()) {
            new ChangePassUI().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
            return;
        }
    }//GEN-LAST:event_mnidoimatkhauActionPerformed

    private void mniloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniloginActionPerformed
        if(Auth.isLogin()) {
           MsgBox.alert(this, "Bạn đã đăng nhập !");
           return;
        } else {
            openDangnhap();
        }
    }//GEN-LAST:event_mniloginActionPerformed

    private void mnihuongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihuongdanActionPerformed
        openHuongdan();
    }//GEN-LAST:event_mnihuongdanActionPerformed

    private void mnidangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidangxuatActionPerformed
        openDangxuat();
    }//GEN-LAST:event_mnidangxuatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openDangxuat();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        openHuongdan();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void mniketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniketthucActionPerformed
        openKetthuc();
    }//GEN-LAST:event_mniketthucActionPerformed

    private void mnibangdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnibangdiemActionPerformed
        openThongke(WIDTH);
    }//GEN-LAST:event_mnibangdiemActionPerformed

    private void mnichuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnichuyendeActionPerformed
        openChuyende();
    }//GEN-LAST:event_mnichuyendeActionPerformed

    private void mnikhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikhoahocActionPerformed
        openKhoahoc();
    }//GEN-LAST:event_mnikhoahocActionPerformed

    private void mnihocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnihocvienActionPerformed
        openHocvien();
    }//GEN-LAST:event_mnihocvienActionPerformed

    private void btnchuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuyendeActionPerformed
        openChuyende();
    }//GEN-LAST:event_btnchuyendeActionPerformed

    private void btnnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnguoihocActionPerformed
        openNguoihoc();
    }//GEN-LAST:event_btnnguoihocActionPerformed

    private void btnkhoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhoahocActionPerformed
        openKhoahoc();
    }//GEN-LAST:event_btnkhoahocActionPerformed

    private void btnhocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhocvienActionPerformed
        openHocvien();
    }//GEN-LAST:event_btnhocvienActionPerformed

    private void mnigioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnigioithieuActionPerformed
        openGioithieu();
    }//GEN-LAST:event_mnigioithieuActionPerformed

    private void mnuthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuthongkeActionPerformed
        openThongke(WIDTH);
    }//GEN-LAST:event_mnuthongkeActionPerformed

    private void mniluongnguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniluongnguoihocActionPerformed
        openThongke(WIDTH);
    }//GEN-LAST:event_mniluongnguoihocActionPerformed

    private void mnidiemcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidiemcdActionPerformed
        openThongke(WIDTH);
    }//GEN-LAST:event_mnidiemcdActionPerformed

    private void mnidoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnidoanhthuActionPerformed
        openThongke(WIDTH);
    }//GEN-LAST:event_mnidoanhthuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchuyende;
    private javax.swing.JButton btnhocvien;
    private javax.swing.JButton btnketthuc;
    private javax.swing.JButton btnkhoahoc;
    private javax.swing.JButton btnnguoihoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblcock;
    private javax.swing.JMenuItem mnibangdiem;
    private javax.swing.JMenuItem mnichuyende;
    private javax.swing.JMenuItem mnidangxuat;
    private javax.swing.JMenuItem mnidiemcd;
    private javax.swing.JMenuItem mnidoanhthu;
    private javax.swing.JMenuItem mnidoimatkhau;
    private javax.swing.JMenuItem mnigioithieu;
    private javax.swing.JMenuItem mnihocvien;
    private javax.swing.JMenuItem mnihuongdan;
    private javax.swing.JMenuItem mniketthuc;
    private javax.swing.JMenuItem mnikhoahoc;
    private javax.swing.JMenuItem mnilogin;
    private javax.swing.JMenuItem mniluongnguoihoc;
    private javax.swing.JMenuItem mninguoihoc;
    private javax.swing.JMenuItem mninhanvien;
    private javax.swing.JMenu mnuhethong;
    private javax.swing.JMenu mnuquanly;
    private javax.swing.JMenu mnuthongke;
    private javax.swing.JMenu mnutrogiup;
    // End of variables declaration//GEN-END:variables

    private void openHuongdan() {
        if (Auth.isLogin()) {
            try {
                Desktop.getDesktop().browse(new File("User manual/index.html").toURI());
            } catch (IOException e) {
                MsgBox.alert(this, "Không tìm thấy file hướng dẫn !");
                return;
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openDangxuat() {
        Auth.clear();
        new MainUI().setVisible(true);
        dispose();
    }

    private void openDangnhap() {
        Auth.clear();
        new LoginUI().setVisible(true);
        dispose();
    }

    private void openKetthuc() {
        if (MsgBox.confirm(this, "Bạn có chắc muốn kết thúc ?")) {
            System.exit(0);
        }
    }

    private void openNhanvien() {
        if (Auth.isLogin()) {
            new ManaStaff().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openNguoihoc() {
        if (Auth.isLogin()) {
            new ManaLearner().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openChuyende() {
        if (Auth.isLogin()) {
            new ManaObjects().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openKhoahoc() {
        if (Auth.isLogin()) {
            new ManaCourse().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openHocvien() {
        if (Auth.isLogin()) {
            new ManaStudents().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openGioithieu() {
        if (Auth.isLogin()) {
            new IntroUI().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }

    private void openThongke(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền xem thông tin doanh thu !");
            } else {
                Statistics tk = new Statistics();
                tk.setVisible(true);
                tk.selectTab(index);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập !");
        }
    }
}
